CREATE SCHEMA SQLFDEMO;
SET SCHEMA SQLFDEMO;

CREATE ASYNCEVENTLISTENER DEMOLISTENER (
	LISTENERCLASS 'com.vmware.sqlfire.callbacks.DBSynchronizer' 
	INITPARAMS 'com.mysql.jdbc.Driver,jdbc:mysql://10.28.229.148:3306/SQLFDEMO?user=sqlfdemo&password=sqlfdemo'
) SERVER GROUPS (DBSYNC);

CREATE TABLE REQUESTS (
  REQUEST_ID VARCHAR(100) NOT NULL,
  REQUEST_ON TIMESTAMP NOT NULL,
  REQUEST_ORDERS INTEGER NOT NULL,
  REQUEST_ITEMS INTEGER NOT NULL,
  REQUEST_DURATION INTEGER NOT NULL,
  PRIMARY KEY (REQUEST_ID)
) PARTITION BY (REQUEST_ID)
ASYNCEVENTLISTENER (DEMOLISTENER);

CREATE TABLE ORDERS
(
    ORDER_ID VARCHAR(100) NOT NULL,
    REQUEST_ID VARCHAR(100) NOT NULL,
    ORDER_ON TIMESTAMP NOT NULL,
    PRIMARY KEY (ORDER_ID)
) PARTITION BY (REQUEST_ID)
  COLOCATE WITH (REQUESTS);

CREATE TABLE ITEMS
(
    ITEM_ID VARCHAR(100) NOT NULL,
    ORDER_ID VARCHAR(100) NOT NULL,
    ITEM_NAME VARCHAR(50) NOT NULL,
    ITEM_PRICE DOUBLE NOT NULL,
    PRIMARY KEY (ITEM_ID)
) PARTITION BY (ORDER_ID)
  COLOCATE WITH (ORDERS);

  
CALL SYS.START_ASYNC_EVENT_LISTENER('DEMOLISTENER');


