
CREATE TABLE REQUESTS (
  REQUEST_ID VARCHAR(100) NOT NULL,
  REQUEST_ON DATETIME NOT NULL,
  REQUEST_ORDERS INT(11) NOT NULL,
  REQUEST_ITEMS INT(11) NOT NULL,
  REQUEST_DURATION BIGINT(20) NOT NULL,
  PRIMARY KEY (REQUEST_ID),
  UNIQUE KEY CUSTOMER_ID_UQ (REQUEST_ID)
);

CREATE TABLE ORDERS (
  ORDER_ID VARCHAR(100) NOT NULL,
  REQUEST_ID VARCHAR(100) NOT NULL,
  ORDER_ON DATETIME NOT NULL,
  PRIMARY KEY (ORDER_ID),
  UNIQUE KEY ORDER_ID_UQ (ORDER_ID)
);

CREATE TABLE ITEMS (
  ITEM_ID VARCHAR(100) NOT NULL,
  ORDER_ID VARCHAR(100) NOT NULL,
  ITEM_NAME VARCHAR(50) NOT NULL,
  ITEM_PRICE DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (ITEM_ID),
  UNIQUE KEY ITEM_ID_UQ (ITEM_ID)
);




